pull_request_rules:
    - name: Automatic merge
      description: Merge when dependency update PR passes all branch protection
      conditions:
          - or:
                - author = dependabot[bot]
                - author = renovate[bot]
      actions:
          merge:
