const Fonts = [
    'Anonymous Pro',
    'Arial',
    'Arvo',
    'Asap',
    'Dosis',
    'Droid Sans',
    'Droid Serif',
    'Inconsolata',
    'Lato',
    'Lora',
    'Maven Pro',
    'Maven Pro',
    'Merriweather',
    'Montserrat',
    'Muli',
    'Open Sans Condensed',
    'Oswald',
    'Ovo',
    'Oxygen',
    'PT Mono',
    'PT Sans Narrow',
    'PT Sans',
    'PT Serif',
    'Raleway',
    'Roboto Condensed',
    'Roboto Slab',
    'Roboto',
    'Source Code Pro',
    'Source Sans Pro',
    'Tahoma',
    'Times',
    'Titillium Web',
    'Ubuntu'
];

export default Fonts;
